### ISSUE TITLE
Volspotconnect not starting: ECONNREFUSED

### ISSUE THREAD

**Issue by mjunyent** [balbuze/volumio-plugins#10]
Hello,

I had volspotconnect working correctly until I updated volumio and installed a hifiberry plus. So it seems one of those things has broken volspotconnect.

When it starts I get ECONNREFUSED error:
`2016-12-14T09:52:14.651Z - info: Enabling plugin volspotconnect
2016-12-14T09:52:14.656Z - info: Loading plugin "volspotconnect"...
2016-12-14T09:52:14.662Z - info: Applying required configuration parameters for plugin volspotconnect
2016-12-14T09:52:14.734Z - info: Volspotconnect Daemon Started
2016-12-14T09:52:19.739Z - info: Connecting to daemon
2016-12-14T09:52:19.744Z - info: Volspotcoonect status error:
2016-12-14T09:52:19.745Z - info:  Error: connect ECONNREFUSED 127.0.0.1:4000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
2016-12-14T09:52:19.747Z - info: Volspotconnect status error:
2016-12-14T09:52:19.748Z - info:  Error: connect ECONNREFUSED 127.0.0.1:4000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)`

By looking at the opened issues I thought it was because of the hifiberry but I have the correct device:
`cat /data/plugins/music_service/volspotconnect/spotify-connect-web/startconnect.sh` returns
`./spotify-connect-web  --username 'xxx' --password 'xxx' --bitrate 320 --name 'Volumio' --playback_device plughw:1 --mixer 'Digital'  --mixer_device_index 1 --dbrange 45 # &
avahi-publish-service -s 'Volumio' _spotify-connect._tcp 4000 VERSION=1.0 CPath=/login/_zeroconf`

And `aplay -l`
`**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0`

Also, just by running startconnect.sh I can get spotify connect working.

Where can the problem be?

**Comment by balbuze** [comment]
Humm. It is weird if it starts when entering startconnect.sh as the plugin launch the same command. I suppose you have reboot? And of course plugin is enabled. What is your device ? RPI 1,2,3,0 ?

**Comment by balbuze** [comment]
A connection refused is due to a non working daemon or a already working (launched by hand before the plugin)

**Comment by mjunyent** [comment]
RPI 3

But it's already fixed after a reboot. I did a reboot but I was already tinkering with shutting off and on the plugin and I suppose that's why it kept failing.

Thank you very much!
