### ISSUE TITLE
[volstereo2mono] Stuck on install

### ISSUE THREAD

**Issue by messismore** [balbuze/volumio-plugins#131]
Hi, I am trying to install the plugin, but it keeps getting stuck at
```
Progress: 60
Status :Copying Plugin into location
```

Here's what I did:
```
volumio@wohnzimmer:/mnt/INTERNAL/volstereo2mono$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
/bin/mv: cannot stat '*.zip': No such file or directory
child_process.js:524
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/volstereo2mono.zip
/bin/mv: cannot stat '*.zip': No such file or directory

    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at install (/volumio/pluginhelper.js:659:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:719:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

```
Okay, so that didn't work, I assume because the creates a `.tar.gz` but looks for a `.zip` afterwards? Guess I'll just copy the original `volstereo2mono.zip` into `/mnt/INTERNAL/volstereo2mono`:
```
volumio@wohnzimmer:/mnt/INTERNAL/volstereo2mono$ sudo chmod a+rwx volstereo2mono.zip
volumio@wohnzimmer:/mnt/INTERNAL/volstereo2mono$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
/bin/mv: cannot remove 'volstereo2mono.zip': Permission denied
child_process.js:524
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/volstereo2mono.zip
/bin/mv: cannot remove 'volstereo2mono.zip': Permission denied

    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at install (/volumio/pluginhelper.js:659:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:719:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
volumio@wohnzimmer:/mnt/INTERNAL/volstereo2mono$ sudo volumio plugin install
[sudo] password for volumio: 

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 30
Status :Creating folder on disk
Progress: 40
Status :Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Progress: 60
Status :Copying Plugin into location
```

It never gets past this… Is there a way to get it to work?

**Comment by balbuze** [comment]
try this : 
'
cd /data/INTERNAL
 wget https://github.com/balbuze/volumio-plugins/raw/master/plugins/audio_interface/volstereo2mono/volstereo2mono.zip
miniunzip volstereo2mono
volumio plugin install
'

**Comment by messismore** [comment]
Worked! Thank you so much for this plugin! Having only the right channel got old fast…
