### ISSUE TITLE
Inappropiate ioctl for device

### ISSUE THREAD

**Issue by haup** [balbuze/volumio-plugins#216]
After installing  the latest Volumio version (2.565), I also updated the volconnect2 plugin as well. It initially crashed with the following log output:

```
Mar 17 12:25:34 beatbox systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Mar 17 12:25:34 beatbox systemd[1]: Unit volspotconnect2.service entered failed state.
Mar 17 12:25:35 beatbox systemd[1]: Stopping Volspotconnect2 Daemon...
Mar 17 12:25:35 beatbox systemd[1]: Starting Volspotconnect2 Daemon...
Mar 17 12:25:35 beatbox systemd[1]: Started Volspotconnect2 Daemon.
Mar 17 12:25:35 beatbox volumio[11109]: vollibrespot v0.1.3 48346b7 2019-02-25 (librespot 57c9ab5 2019-02-22) -- Built On 2019-02-25
Mar 17 12:25:35 beatbox volumio[11109]: thread 'main' panicked at 'Invalid bitrate: ()', libcore/result.rs:1009:5
Mar 17 12:25:35 beatbox volumio[11109]: stack backtrace:
Mar 17 12:25:35 beatbox systemd[1]: Started Volspotconnect2 Daemon.
Mar 17 12:25:35 beatbox volumio[11109]: 0:   0x9b0c4f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h3608b871673a8803
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Mar 17 12:25:35 beatbox volumio[11109]: 1:   0x9a0547 - std::sys_common::backtrace::print::hef947be8cf8e8f55
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/sys_common/backtrace.rs:71
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/sys_common/backtrace.rs:59
Mar 17 12:25:35 beatbox volumio[11109]: 2:   0x99e083 - std::panicking::default_hook::{{closure}}::haac47ed356699ffe
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/panicking.rs:211
Mar 17 12:25:35 beatbox volumio[11109]: 3:   0x99dcfb - std::panicking::default_hook::h95ba73384225983b
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/panicking.rs:227
Mar 17 12:25:35 beatbox volumio[11109]: 4:   0x99e7ab - std::panicking::rust_panic_with_hook::ha1106c0ce43cea72
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/panicking.rs:477
Mar 17 12:25:35 beatbox volumio[11109]: 5:   0x99e36f - std::panicking::continue_panic_fmt::h875c7946721c05c9
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/panicking.rs:391
Mar 17 12:25:35 beatbox volumio[11109]: 6:   0x99e257 - rust_begin_unwind
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/panicking.rs:326
Mar 17 12:25:35 beatbox volumio[11109]: 7:   0x9eeb43 - core::panicking::panic_fmt::h429a06507aba9228
Mar 17 12:25:35 beatbox volumio[11109]: at libcore/panicking.rs:77
Mar 17 12:25:35 beatbox volumio[11109]: 8:   0x4fd50f - core::result::unwrap_failed::hf6293151d0e2fda6
Mar 17 12:25:35 beatbox volumio[11109]: 9:   0x4eeb07 - vollibrespot::main::hff5c7bba125530f5
Mar 17 12:25:35 beatbox volumio[11109]: 10:   0x500147 - std::rt::lang_start::{{closure}}::h209c228e7daff9ce
Mar 17 12:25:35 beatbox volumio[11109]: 11:   0x99e1cf - std::panicking::try::do_call::haa4d884de44899fd
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/rt.rs:59
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/panicking.rs:310
Mar 17 12:25:35 beatbox volumio[11109]: 12:   0x9b9c0f - __rust_maybe_catch_panic
Mar 17 12:25:35 beatbox volumio[11109]: at libpanic_unwind/lib.rs:103
Mar 17 12:25:35 beatbox volumio[11109]: 13:   0x99d217 - std::panic::catch_unwind::h90512a021818b18b
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/panicking.rs:289
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/panic.rs:392
Mar 17 12:25:35 beatbox volumio[11109]: 14:   0x99bbd3 - std::rt::lang_start_internal::h2c5a86fd7f2a32eb
Mar 17 12:25:35 beatbox volumio[11109]: at libstd/rt.rs:58
Mar 17 12:25:35 beatbox volumio[11109]: 15:   0x4f046f - main
Mar 17 12:25:35 beatbox volumio[11109]: 16: 0x76d95293 - __libc_start_main
Mar 17 12:25:35 beatbox systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Mar 17 12:25:35 beatbox systemd[1]: Unit volspotconnect2.service entered failed state.
```

But then I switched to bitrate 320 and got the following:

```
Mar 17 12:21:33 beatbox systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Mar 17 12:21:33 beatbox systemd[1]: Unit volspotconnect2.service entered failed state.
Mar 17 12:21:33 beatbox volumio[9165]: at libstd/rt.rs:58
Mar 17 12:21:33 beatbox volumio[9165]: 16:   0x48c46f - main
Mar 17 12:21:33 beatbox volumio[9165]: 17: 0x76d47293 - __libc_start_main
Mar 17 12:21:33 beatbox systemd[1]: Stopping Volspotconnect2 Daemon...
Mar 17 12:21:33 beatbox systemd[1]: Starting Volspotconnect2 Daemon...
Mar 17 12:21:33 beatbox systemd[1]: Started Volspotconnect2 Daemon.
Mar 17 12:21:33 beatbox volumio[9187]: vollibrespot v0.1.3 48346b7 2019-02-25 (librespot 57c9ab5 2019-02-22) -- Built On 2019-02-25
Mar 17 12:21:33 beatbox volumio[9187]: Password for -p: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 25, kind: Other, message: "Inappropriate ioctl for device" }', libcore/result.rs:1009:5
Mar 17 12:21:33 beatbox volumio[9187]: stack backtrace:
Mar 17 12:21:33 beatbox volumio[9187]: 0:   0x96fc4f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h3608b871673a8803
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Mar 17 12:21:33 beatbox volumio[9187]: 1:   0x95f547 - std::sys_common::backtrace::print::hef947be8cf8e8f55
Mar 17 12:21:33 beatbox systemd[1]: Started Volspotconnect2 Daemon.
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/sys_common/backtrace.rs:71
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/sys_common/backtrace.rs:59
Mar 17 12:21:33 beatbox volumio[9187]: 2:   0x95d083 - std::panicking::default_hook::{{closure}}::haac47ed356699ffe
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/panicking.rs:211
Mar 17 12:21:33 beatbox volumio[9187]: 3:   0x95ccfb - std::panicking::default_hook::h95ba73384225983b
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/panicking.rs:227
Mar 17 12:21:33 beatbox volumio[9187]: 4:   0x95d7ab - std::panicking::rust_panic_with_hook::ha1106c0ce43cea72
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/panicking.rs:477
Mar 17 12:21:33 beatbox volumio[9187]: 5:   0x95d36f - std::panicking::continue_panic_fmt::h875c7946721c05c9
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/panicking.rs:391
Mar 17 12:21:33 beatbox volumio[9187]: 6:   0x95d257 - rust_begin_unwind
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/panicking.rs:326
Mar 17 12:21:33 beatbox volumio[9187]: 7:   0x9adb43 - core::panicking::panic_fmt::h429a06507aba9228
Mar 17 12:21:33 beatbox volumio[9187]: at libcore/panicking.rs:77
Mar 17 12:21:33 beatbox volumio[9187]: 8:   0x4bc3bf - core::result::unwrap_failed::hed968dfd37ddc0a3
Mar 17 12:21:33 beatbox volumio[9187]: 9:   0x4bec4b - librespot_core::authentication::get_credentials::h087fb297e6a155dc
Mar 17 12:21:33 beatbox volumio[9187]: 10:   0x4ad65f - vollibrespot::main::hff5c7bba125530f5
Mar 17 12:21:33 beatbox volumio[9187]: 11:   0x4bf147 - std::rt::lang_start::{{closure}}::h209c228e7daff9ce
Mar 17 12:21:33 beatbox volumio[9187]: 12:   0x95d1cf - std::panicking::try::do_call::haa4d884de44899fd
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/rt.rs:59
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/panicking.rs:310
Mar 17 12:21:33 beatbox volumio[9187]: 13:   0x978c0f - __rust_maybe_catch_panic
Mar 17 12:21:33 beatbox volumio[9187]: at libpanic_unwind/lib.rs:103
Mar 17 12:21:33 beatbox volumio[9187]: 14:   0x95c217 - std::panic::catch_unwind::h90512a021818b18b
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/panicking.rs:289
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/panic.rs:392
Mar 17 12:21:33 beatbox volumio[9187]: 15:   0x95abd3 - std::rt::lang_start_internal::h2c5a86fd7f2a32eb
Mar 17 12:21:33 beatbox volumio[9187]: at libstd/rt.rs:58
Mar 17 12:21:33 beatbox volumio[9187]: 16:   0x4af46f - main
Mar 17 12:21:33 beatbox volumio[9187]: 17: 0x76d4e293 - __libc_start_main
Mar 17 12:21:33 beatbox systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Mar 17 12:21:33 beatbox systemd[1]: Unit volspotconnect2.service entered failed state.
Mar 17 12:21:33 beatbox systemd[1]: Stopping Volspotconnect2 Daemon...
Mar 17 12:21:33 beatbox systemd[1]: Starting Volspotconnect2 Daemon...
Mar 17 12:21:33 beatbox systemd[1]: volspotconnect2.service start request repeated too quickly, refusing to start.
Mar 17 12:21:33 beatbox systemd[1]: Failed to start Volspotconnect2 Daemon.
Mar 17 12:21:33 beatbox systemd[1]: Unit volspotconnect2.service entered failed state.
Mar 17 12:21:33 beatbox systemd[1]: Starting Volspotconnect2 Daemon...
Mar 17 12:21:33 beatbox systemd[1]: volspotconnect2.service start request repeated too quickly, refusing to start.
Mar 17 12:21:33 beatbox systemd[1]: Failed to start Volspotconnect2 Daemon.
Mar 17 12:21:33 beatbox systemd[1]: Starting Volspotconnect2 Daemon...
Mar 17 12:21:33 beatbox systemd[1]: volspotconnect2.service start request repeated too quickly, refusing to start.
Mar 17 12:21:33 beatbox systemd[1]: Failed to start Volspotconnect2 Daemon.
Mar 17 12:21:33 beatbox systemd[1]: Starting Volspotconnect2 Daemon...
Mar 17 12:21:33 beatbox systemd[1]: volspotconnect2.service start request repeated too quickly, refusing to start.
Mar 17 12:21:33 beatbox systemd[1]: Failed to start Volspotconnect2 **Daemon.** ```

**Comment by balbuze** [comment]
is it an update or a fresh install?

**Comment by haup** [comment]
Its an update! by the way plugin version is 0.9.1. The one, which is selectable on the plugins tab. I tried an downgrad to version 0.9.0, but the problem still occured.

**Comment by haup** [comment]
I tried a fresh install today and the problem didn´t show up. So I think it is related to the upgrade or leftovers from an older version of volumio or the plugin itself! Close

**Comment by balbuze** [comment]
Thanks for giving the info
