### ISSUE TITLE
Updated to 0.95, now can't connect from any device

### ISSUE THREAD

**Issue by Hellwo** [balbuze/volumio-plugins#235]
I just updated my volumio and all plugins, now I can't connect from any spotify client (Windows, Mac, iOS). 
Here is the log-File while trying to connect from Spotify on Windows:

```
volumio@volumiorpi0w_1:/var/log$` sudo journalctl -f -u volspotconnect2.service
-- Logs begin at Thu 2019-05-30 20:37:00 UTC. --
May 30 20:56:19 volumiorpi0w_1 volumio[2023]: at src/libstd/panic.rs:388
May 30 20:56:19 volumiorpi0w_1 volumio[2023]: at src/libstd/rt.rs:48
May 30 20:56:19 volumiorpi0w_1 volumio[2023]: 27:   0x486bff - main
May 30 20:56:19 volumiorpi0w_1 volumio[2023]: 28: 0xb6cbd293 - __libc_start_main
May 30 20:56:21 volumiorpi0w_1 systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
May 30 20:56:21 volumiorpi0w_1 systemd[1]: Stopping Volspotconnect2 Daemon...
May 30 20:56:21 volumiorpi0w_1 systemd[1]: Starting Volspotconnect2 Daemon...
May 30 20:56:21 volumiorpi0w_1 systemd[1]: Started Volspotconnect2 Daemon.
May 30 20:56:21 volumiorpi0w_1 volumio[2209]: vollibrespot v0.1.6 cd3b133 2019-04-29 (librespot b5c80bf 2018-11-27) -- Built On 20                           19-04-29
May 30 20:56:21 volumiorpi0w_1 volumio[2209]: [Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, messa                           ge: "No such device" }
May 30 20:57:47 volumiorpi0w_1 volumio[2209]: [Vollibrespot] : Connecting to AP "gew1-accesspoint-a-hv89.ap.spotify.com:4070"
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: [Vollibrespot] : Authenticated as "1170287921" !
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: [Vollibrespot] : Setting up new mixer: card:hw:1 mixer:undefined index:0
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: thread 'main' panicked at 'Couldn't find SelemId', src/libcore/option.rs:1038:5
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: stack backtrace:
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 0:   0xa04bab - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hdf951eb9                           f43ea27e
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 1:   0xa005af - std::sys_common::backtrace::_print::h2b5fdbbb5020ccf8
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/sys_common/backtrace.rs:70
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 2:   0xa02c4b - std::panicking::default_hook::{{closure}}::h18d8c59665918d69
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/sys_common/backtrace.rs:58
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:200
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 3:   0xa02883 - std::panicking::default_hook::h1fd1ad969274543a
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:215
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 4:   0xa033bb - std::panicking::rust_panic_with_hook::h40a77253872948e8
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:478
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 5:   0xa02f3b - std::panicking::continue_panic_fmt::hec94fc8e5daf641b
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:385
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 6:   0xa02e27 - rust_begin_unwind
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:312
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 7:   0xa183f3 - core::panicking::panic_fmt::h74ee8034b317ceed
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libcore/panicking.rs:85
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 8:   0xa18463 - core::option::expect_failed::hbc312d76c0b547f0
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libcore/option.rs:1038
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 9:   0x5a7e67 - <librespot_playback::mixer::alsamixer::AlsaMixer as librespot_playba                           ck::mixer::Mixer>::open::ha244959311d89d8a
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 10:   0x4f619f - librespot_playback::mixer::mk_sink::h6d7d1629f7ca5170
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 11:   0x507987 - <vollibrespot::Main as futures::future::Future>::poll::hf7338b1bdf7                           b29a4
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 12:   0x52a0e3 - futures::task_impl::std::set::h1f971335a50ca5c0
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 13:   0x5038db - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::pol                           l::h96fa17930c2b12b0
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 14:   0x52a3f3 - futures::task_impl::std::set::h8d115a2d1cb40712
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 15:   0x50f91b - <std::thread::local::LocalKey<T>>::with::hb352fc0f58f130d7
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 16:   0x52983f - <tokio_current_thread::Entered<'a, P>>::block_on::h2609ff85370e0451
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 17:   0x50f047 - <std::thread::local::LocalKey<T>>::with::h66f130bf03df2340
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 18:   0x50f507 - <std::thread::local::LocalKey<T>>::with::h6d733bb5456b63c9
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 19:   0x50eb4b - <std::thread::local::LocalKey<T>>::with::h2c3ef5154130d9b7
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 20:   0x528833 - <scoped_tls::ScopedKey<T>>::set::h0f9eb81c519fac17
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 21:   0x519afb - tokio_core::reactor::Core::run::h545028c332d4af18
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 22:   0x5088a7 - vollibrespot::main::h393279e1f565f771
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 23:   0x514093 - std::rt::lang_start::{{closure}}::hb2a63859d18ee1ea
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 24:   0xa02d9f - std::panicking::try::do_call::h287c6909aadcc5f1
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/rt.rs:49
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:297
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 25:   0xa07aaf - __rust_maybe_catch_panic
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libpanic_unwind/lib.rs:92
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 26:   0xa03833 - std::rt::lang_start_internal::h747c58e2c78f4f4f
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:276
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panic.rs:388
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/rt.rs:48
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 27:   0x508bff - main
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 28: 0xb6d1e293 - __libc_start_main
May 30 20:57:48 volumiorpi0w_1 systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
May 30 20:57:48 volumiorpi0w_1 systemd[1]: Unit volspotconnect2.service entered failed state.
May 30 20:57:50 volumiorpi0w_1 systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
May 30 20:57:50 volumiorpi0w_1 systemd[1]: Stopping Volspotconnect2 Daemon...
May 30 20:57:50 volumiorpi0w_1 systemd[1]: Starting Volspotconnect2 Daemon...
May 30 20:57:50 volumiorpi0w_1 systemd[1]: Started Volspotconnect2 Daemon.
May 30 20:57:51 volumiorpi0w_1 volumio[2319]: vollibrespot v0.1.6 cd3b133 2019-04-29 (librespot b5c80bf 2018-11-27) -- Built On 20                           19-04-29
May 30 20:57:51 volumiorpi0w_1 volumio[2319]: [Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, messa                           ge: "No such device" }
volumio@volumiorpi0w_1:/var/log$ sudo journalctl -f -u volspotconnect2.service
-- Logs begin at Thu 2019-05-30 20:37:00 UTC. --
May 30 20:56:19 volumiorpi0w_1 volumio[2023]: at src/libstd/panic.rs:388
May 30 20:56:19 volumiorpi0w_1 volumio[2023]: at src/libstd/rt.rs:48
May 30 20:56:19 volumiorpi0w_1 volumio[2023]: 27:   0x486bff - main
May 30 20:56:19 volumiorpi0w_1 volumio[2023]: 28: 0xb6cbd293 - __libc_start_main
May 30 20:56:21 volumiorpi0w_1 systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
May 30 20:56:21 volumiorpi0w_1 systemd[1]: Stopping Volspotconnect2 Daemon...
May 30 20:56:21 volumiorpi0w_1 systemd[1]: Starting Volspotconnect2 Daemon...
May 30 20:56:21 volumiorpi0w_1 systemd[1]: Started Volspotconnect2 Daemon.
May 30 20:56:21 volumiorpi0w_1 volumio[2209]: vollibrespot v0.1.6 cd3b133 2019-04-29 (librespot b5c80bf 2018-11-27) -- Built On 20                           19-04-29
May 30 20:56:21 volumiorpi0w_1 volumio[2209]: [Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, messa                           ge: "No such device" }
May 30 20:57:47 volumiorpi0w_1 volumio[2209]: [Vollibrespot] : Connecting to AP "gew1-accesspoint-a-hv89.ap.spotify.com:4070"
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: [Vollibrespot] : Authenticated as "1170287921" !
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: [Vollibrespot] : Setting up new mixer: card:hw:1 mixer:undefined index:0
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: thread 'main' panicked at 'Couldn't find SelemId', src/libcore/option.rs:1038:5
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: stack backtrace:
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 0:   0xa04bab - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hdf951eb9                           f43ea27e
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 1:   0xa005af - std::sys_common::backtrace::_print::h2b5fdbbb5020ccf8
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/sys_common/backtrace.rs:70
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 2:   0xa02c4b - std::panicking::default_hook::{{closure}}::h18d8c59665918d69
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/sys_common/backtrace.rs:58
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:200
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 3:   0xa02883 - std::panicking::default_hook::h1fd1ad969274543a
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:215
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 4:   0xa033bb - std::panicking::rust_panic_with_hook::h40a77253872948e8
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:478
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 5:   0xa02f3b - std::panicking::continue_panic_fmt::hec94fc8e5daf641b
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:385
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 6:   0xa02e27 - rust_begin_unwind
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libstd/panicking.rs:312
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 7:   0xa183f3 - core::panicking::panic_fmt::h74ee8034b317ceed
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libcore/panicking.rs:85
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 8:   0xa18463 - core::option::expect_failed::hbc312d76c0b547f0
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: at src/libcore/option.rs:1038
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 9:   0x5a7e67 - <librespot_playback::mixer::alsamixer::AlsaMixer as librespot_playba                           ck::mixer::Mixer>::open::ha244959311d89d8a
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 10:   0x4f619f - librespot_playback::mixer::mk_sink::h6d7d1629f7ca5170
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 11:   0x507987 - <vollibrespot::Main as futures::future::Future>::poll::hf7338b1bdf7                           b29a4
May 30 20:57:48 volumiorpi0w_1 volumio[2209]: 12:   0x52a0e3 - futures::task_impl::std::set::h1f971335a50ca5c0
May 30 20:57:48
```

Any recommendations how to fix this?

**Comment by Hellwo** [comment]
Okay, after I read https://github.com/balbuze/volumio-plugins/issues/212 I changed  the mixer settings once to hardware and now it's working again, even when I changed the mixer back to none

**Comment by Hellwo** [comment]
That worked only temporary. When the raspberry is idle for more than some hours the problem reoccurs. Then I have to go to the playback setting and just hit save under the mixer setting without making any changes. After that Spotify is able to connect to the device. But I have to repeat this process every day

**Comment by didumir** [comment]
Same here on a x86 box, mixer can be off, sw, hw, always volspotconnect2.service: main process exited, code=exited, status=101/n/a

**Comment by didumir** [comment]
> Same here on a x86 box, mixer can be off, sw, hw, always volspotconnect2.service: main process exited, code=exited, status=101/n/a

Its working again for me:
- uninstalled & reinstalled the latest version of the plugin -> not working
- changed 'multi-user device' to off -> not working
- changed 'multi-user device' back to on -> WORKING

**Comment by didumir** [comment]
> Its working again for me:

And stopped again working... no changes in the system, simple rebooting after two days :(
