### ISSUE TITLE
librespot panic

### ISSUE THREAD

**Issue by joshwapohlmann** [balbuze/volumio-plugins#251]
I tried installing volspotconnect2 v0.9.9 to a volumio v2.657.
When trying to connect with an android device (using latest spotify app) I can log this error:

```
ec 20 11:53:24 volumio volumio[1756]: [SpotifyConnect] Vollibrespot Daemon Started
Dec 20 11:53:24 volumio volumio[4785]: [Vollibrespot] librespot_connect::discovery: Zeroconf server listening on 0.0.0.0:45893
Dec 20 11:53:24 volumio volumio[4785]: [Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
Dec 20 11:53:27 volumio sudo[4807]: volumio : TTY=pts/0 ; PWD=/tmp/volspotconnect2 ; USER=root ; COMMAND=/bin/journalctl -f
Dec 20 11:53:27 volumio sudo[4807]: pam_unix(sudo:session): session opened for user root by volumio(uid=0)
Dec 20 11:53:35 volumio volumio[1756]: info: CoreCommandRouter::volumioGetState
Dec 20 11:53:35 volumio volumio[1756]: info: CoreStateMachine::getState
Dec 20 11:53:35 volumio volumio[1756]: info: CorePlayQueue::getTrack 0
Dec 20 11:53:35 volumio volumio[1756]: info: Listing playlists
Dec 20 11:53:35 volumio volumio[1756]: info: Listing playlists
Dec 20 11:53:37 volumio volumio[4785]: [Vollibrespot] : ConnectRequest: "Spotify/8.5.33 Android/29 (MI 9)"
Dec 20 11:53:37 volumio volumio[4785]: [Vollibrespot] librespot_connect::discovery: ConnectRequest: Some("action=getInfo")
Dec 20 11:53:40 volumio volumio[4785]: [Vollibrespot] : ConnectRequest: "Spotify/8.5.33 Android/29 (MI 9)"
Dec 20 11:53:40 volumio volumio[4785]: [Vollibrespot] librespot_connect::discovery: ConnectRequest: None
Dec 20 11:53:40 volumio volumio[4785]: [Vollibrespot] librespot_connect::discovery: POST "/" {}
Dec 20 11:53:40 volumio volumio[4785]: [Vollibrespot] : Connecting to AP "gew1-accesspoint-a-z15g.ap.spotify.com:4070"
Dec 20 11:53:40 volumio volumio[4785]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }', src/libcore/result.rs:1084:5
Dec 20 11:53:40 volumio volumio[4785]: stack backtrace:
Dec 20 11:53:40 volumio volumio[4785]: 0:   0xa2e788 - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
Dec 20 11:53:40 volumio volumio[4785]: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
Dec 20 11:53:40 volumio volumio[4785]: 1:   0xa2e788 - backtrace::backtrace::trace_unsynchronized::h244e30b4d61a86e0
Dec 20 11:53:40 volumio volumio[4785]: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
Dec 20 11:53:40 volumio volumio[4785]: 2:   0xa2e788 - std::sys_common::backtrace::_print::h978df54e55c6209d
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/sys_common/backtrace.rs:47
Dec 20 11:53:40 volumio volumio[4785]: 3:   0xa2e788 - std::sys_common::backtrace::print::ha75ae47f14b8f7f3
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/sys_common/backtrace.rs:36
Dec 20 11:53:40 volumio volumio[4785]: 4:   0xa2e788 - std::panicking::default_hook::{{closure}}::h004e1d529e652ede
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/panicking.rs:200
Dec 20 11:53:40 volumio volumio[4785]: 5:   0xa2e380 - std::panicking::default_hook::h185ef7ff1eea4221
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/panicking.rs:214
Dec 20 11:53:40 volumio volumio[4785]: 6:   0xa2ef44 - std::panicking::rust_panic_with_hook::hfe0a86ed15580d4a
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/panicking.rs:477
Dec 20 11:53:40 volumio volumio[4785]: 7:   0xa2eb10 - std::panicking::continue_panic_fmt::h182e68ecbb1c932b
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/panicking.rs:384
Dec 20 11:53:40 volumio volumio[4785]: 8:   0xa2e9fc - rust_begin_unwind
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/panicking.rs:311
Dec 20 11:53:40 volumio volumio[4785]: 9:   0xa45444 - core::panicking::panic_fmt::h7e9f94035af782b3
Dec 20 11:53:40 volumio volumio[4785]: at src/libcore/panicking.rs:85
Dec 20 11:53:40 volumio volumio[4785]: 10:   0xa45534 - core::result::unwrap_failed::hf7591c1dd9412006
Dec 20 11:53:40 volumio volumio[4785]: at src/libcore/result.rs:1084
Dec 20 11:53:40 volumio volumio[4785]: 11:   0x4aff04 - <vollibrespot::Main as futures::future::Future>::poll::hb49550d8e3f467fa
Dec 20 11:53:40 volumio volumio[4785]: 12:   0x4d59b4 - futures::task_impl::std::set::hb572c3af727256ac
Dec 20 11:53:40 volumio volumio[4785]: 13:   0x4ade2c - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::hc872efa618c45de3
Dec 20 11:53:40 volumio volumio[4785]: 14:   0x4d583c - futures::task_impl::std::set::ha1da852080a54e89
Dec 20 11:53:40 volumio volumio[4785]: 15:   0x49a894 - std::thread::local::LocalKey<T>::with::hb33a14aa0d64830e
Dec 20 11:53:40 volumio volumio[4785]: 16:   0x490c1c - tokio_current_thread::Entered<P>::block_on::h6c7f92e99b77886b
Dec 20 11:53:40 volumio volumio[4785]: 17:   0x49a6b4 - std::thread::local::LocalKey<T>::with::h9ec9ec76b26e7edf
Dec 20 11:53:40 volumio volumio[4785]: 18:   0x49a30c - std::thread::local::LocalKey<T>::with::h26f52d592cd722ab
Dec 20 11:53:40 volumio volumio[4785]: 19:   0x49a16c - std::thread::local::LocalKey<T>::with::h22d8fcf69243240c
Dec 20 11:53:40 volumio volumio[4785]: 20:   0x4901e0 - scoped_tls::ScopedKey<T>::set::h3380ded7e37a7882
Dec 20 11:53:40 volumio volumio[4785]: 21:   0x4c9ee4 - tokio_core::reactor::Core::run::h9c6fa799f1a72320
Dec 20 11:53:40 volumio volumio[4785]: 22:   0x4b23ec - vollibrespot::main::h551d8fa54606fabf
Dec 20 11:53:40 volumio volumio[4785]: 23:   0x4b90ac - std::rt::lang_start::{{closure}}::hdc0b123e45936b4e
Dec 20 11:53:40 volumio volumio[4785]: 24:   0xa2e974 - std::rt::lang_start_internal::{{closure}}::h923917fc45a67b03
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/rt.rs:49
Dec 20 11:53:40 volumio volumio[4785]: 25:   0xa2e974 - std::panicking::try::do_call::he118fbfc301d3e1a
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/panicking.rs:296
Dec 20 11:53:40 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Dec 20 11:53:40 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
Dec 20 11:53:40 volumio volumio[4785]: 26:   0xa32e54 - __rust_maybe_catch_panic
Dec 20 11:53:40 volumio volumio[4785]: at src/libpanic_unwind/lib.rs:80
Dec 20 11:53:40 volumio volumio[4785]: 27:   0xa2f3c0 - std::panicking::try::hcc03ea850c2702cb
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/panicking.rs:275
Dec 20 11:53:40 volumio volumio[4785]: 28:   0xa2f3c0 - std::panic::catch_unwind::hf09eaf9043e449c8
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/panic.rs:394
Dec 20 11:53:40 volumio volumio[4785]: 29:   0xa2f3c0 - std::rt::lang_start_internal::h87508684140f3dc4
Dec 20 11:53:40 volumio volumio[4785]: at src/libstd/rt.rs:48
Dec 20 11:53:40 volumio volumio[4785]: 30:   0x4b33f8 - main
Dec 20 11:53:40 volumio volumio[4785]: 31: 0x76c9d294 - __libc_start_main
Dec 20 11:53:43 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Dec 20 11:53:43 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
Dec 20 11:53:43 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Dec 20 11:53:43 volumio systemd[1]: Started Volspotconnect2 Daemon.
Dec 20 11:53:43 volumio volumio[4855]: vollibrespot v0.1.9 c98fd5d 2019-11-08 (librespot 4674946 2019-11-08) -- Built On 2019-11-08
```
Since the lib is downloaded with the plugin I figured this is not related to the volumio version (which is from october)
Any ideas?

**Comment by joshwapohlmann** [comment]
Has been some time. Noone cares, me neither.
