### ISSUE TITLE
plugin crashes all the time

### ISSUE THREAD

**Issue by CodingGhost** [balbuze/volumio-plugins#279]
Hi,
the Plugin really isnt working for me at all. I have tried it many times, but its super unstable. It will randomly just disconnect, or disconnect on pause/skip etc.

I have some logs ready:

`[Vollibrespot] : Connecting to AP "gew1-accesspoint-b-jb5p.ap.spotify.com:443"
[Vollibrespot] : Authenticated as "vi37elpfrltaj8hldw2k6n4yq" !
[Vollibrespot] : Metadata pipe established
[Vollibrespot] : Country: "DE"
[Vollibrespot] : Event: Volume { volume_to_mixer: 21626 }
[Vollibrespot] : Using alsa sink
[SpotifyConnect]  32.99916075379568
[SpotifyConnect] Volume: Spotify:32.99916075379568 Volumio: 33
info: CoreStateMachine::pushState
info: CoreCommandRouter::volumioPushState
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
[Vollibrespot] : Fetching autoplay context uri
[Vollibrespot] : Event: SessionActive { became_active_at: 1597930601150 }
[Vollibrespot] : SessionActive!
[Vollibrespot] : Event: PlaybackStarted { track_id: SpotifyId { id: 298441256330382875227772083907845405007, audio_type: Track } }
[Vollibrespot] : Event: PlaybackLoading { track_id: SpotifyId { id: 298441256330382875227772083907845405007, audio_type: Track } }
[SpotifyConnect]  A connect session has begun
[SpotifyConnect]  Device palyback is active!
info: CoreCommandRouter::volumioGetState
[SpotifyConnect] Currently active: volspotconnect2
[SpotifyConnect] Not requsting volumioStop on our own service
[SpotifyConnect] Vollibrespot Active
info: CoreCommandRouter::volumioGetState
[SpotifyConnect] Currently active: volspotconnect2
info: CoreCommandRouter::servicePushState
info: CoreStateMachine::pushState
info: CoreCommandRouter::volumioPushState
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
info: CoreCommandRouter::volumioGetState
[SpotifyConnect] Currently active: volspotconnect2
[SpotifyConnect] Pushing new state :: true
info: CoreCommandRouter::servicePushState
info: CoreStateMachine::pushState
info: CoreCommandRouter::volumioPushState
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
[Vollibrespot] : Autoplay uri resolved to <"spotify:station:playlist:6Ym2ETEDTMHYTc8JUSEIop">
[Vollibrespot] : Resolving uri "spotify:station:playlist:6Ym2ETEDTMHYTc8JUSEIop"
[Vollibrespot] : Event: GotToken { token: Token { access_token: "BQDm4-8qQNLISygFp4r4iO9vFyX5jgC9h1dm5wW0cIYo8vYUl4-ZvUuTkE78gbflanRSNxVsdPW-uPc73pLYKP9Z7XfbI725j73RCoxRcm-cI6xtYQMkIrae9ERwQjeArjEmO_r7Jyws3-ysvyJgCdgJIv4haF8fjz2hwmwg6QiTQndfbb9OVKxyzw", expires_in: 3600, token_type: "Bearer", scope: ["streaming", "user-read-playback-state", "user-modify-playback-state", "user-read-currently-playing", "user-read-private"] } }
[SpotifyConnect]  BQDm4-8qQNLISygFp4r4iO9vFyX5jgC9h1dm5wW0cIYo8vYUl4-ZvUuTkE78gbflanRSNxVsdPW-uPc73pLYKP9Z7XfbI725j73RCoxRcm-cI6xtYQMkIrae9ERwQjeArjEmO_r7Jyws3-ysvyJgCdgJIv4haF8fjz2hwmwg6QiTQndfbb9OVKxyzw
[Vollibrespot] : Loading  with Spotify URI 
[SpotifyConnect] Setting VLS device_id: c6e56cf6b68c07041768b06e2f29a439e7724b0e
[Vollibrespot] : Resolved 50 tracks from <"spotify:playlist:6Ym2ETEDTMHYTc8JUSEIop">
[Vollibrespot] :  (265613 ms) loaded
[Vollibrespot] : Event: PlaybackStopped { track_id: SpotifyId { id: 298441256330382875227772083907845405007, audio_type: Track } }
[SpotifyConnect]  Device palyback is inactive
[SpotifyConnect] Device Session is_active: true
[Vollibrespot] : Event: Play { track_id: SpotifyId { id: 298441256330382875227772083907845405007, audio_type: Track }, position_ms: 157048 }
[SpotifyConnect]  play
ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
[Vollibrespot] : Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
[Vollibrespot] : Could not start audio: Alsa error: PCM open failed
ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
[Vollibrespot] : Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
[Vollibrespot] : Could not start audio: Alsa error: PCM open failed
ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
[Vollibrespot] : Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory'
[Vollibrespot] : Could not start audio: Alsa error: PCM open failed
thread '' panicked at 'called `Option::unwrap()` on a `None` value', /build/cache/git/checkouts/librespot-6f197fd632ef9380/659de68/playback/src/audio_backend/alsa.rs:128:19
stack backtrace:
0:   0xaa0828 - backtrace::backtrace::libunwind::trace::h100c6c70e4af496c
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
1:   0xaa0828 - backtrace::backtrace::trace_unsynchronized::hf78ddc194bf45009
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
2:   0xaa0828 - std::sys_common::backtrace::_print_fmt::h967a212a8894e4a4
at src/libstd/sys_common/backtrace.rs:77
3:   0xaa0828 - ::fmt::h5fe383ce2118859a
at src/libstd/sys_common/backtrace.rs:59
4:   0xabc03c - core::fmt::write::h937f59172f6eeeaf
at src/libcore/fmt/mod.rs:1052
5:   0xa9a6ec - std::io::Write::write_fmt::hc70e2634948b89c8
at src/libstd/io/mod.rs:1426
6:   0xaa2cf0 - std::sys_common::backtrace::_print::hbfc81757b29a60f4
at src/libstd/sys_common/backtrace.rs:62
7:   0xaa2cf0 - std::sys_common::backtrace::print::h8bc349c117633211
at src/libstd/sys_common/backtrace.rs:49
8:   0xaa2cf0 - std::panicking::default_hook::{{closure}}::h82c47dcbb8503118
at src/libstd/panicking.rs:204
9:   0xaa2964 - std::panicking::default_hook::hc04800be16711189
at src/libstd/panicking.rs:224
10:   0xaa33a0 - std::panicking::rust_panic_with_hook::h2413ff75e44cd581
at src/libstd/panicking.rs:472
11:   0xaa2fb4 - rust_begin_unwind
at src/libstd/panicking.rs:380
12:   0xab9aa8 - core::panicking::panic_fmt::h2c56481ca2ee7c2f
at src/libcore/panicking.rs:85
13:   0xab9a04 - core::panicking::panic::h858859fb9e6c3f07
at src/libcore/panicking.rs:52
14:   0x66af40 - ::write::h72619216e3588ead
15:   0x645e38 - ::poll::h8c3aa347eb5050fe
16:   0x547b0c - futures::task_impl::std::set::h959dffae037fa8a9
17:   0x542048 - futures::task_impl::Spawn::poll_future_notify::h3ba01a9dfc1d022c
18:   0x54e6d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h53457226459490b1
19:   0x55fe08 - std::panicking::try::do_call::h3a2683b9b75c33db
20:   0xaa75f8 - __rust_maybe_catch_panic
at src/libpanic_unwind/lib.rs:86
21:   0x560140 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he4fab1c16e3e7b3d
22:   0xa93488 -  as core::ops::function::FnOnce>::call_once::h0eb934bdc214e7b7
at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
23:   0xaa68f8 -  as core::ops::function::FnOnce>::call_once::h4eeee9ec160fd74c
at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
24:   0xaa68f8 - std::sys_common::thread::start_thread::hd648575d6de17db0
at src/libstd/sys_common/thread.rs:13
25:   0xaa68f8 - std::sys::unix::thread::Thread::new::thread_start::hc1903f20153f9439
at src/libstd/sys/unix/thread.rs:80
[SpotifyConnect]  The Return
[SpotifyConnect] Pushing metadata
info: CoreCommandRouter::volumioGetState
[SpotifyConnect] Currently active: volspotconnect2
[SpotifyConnect] Pushing new state :: true
info: CoreCommandRouter::servicePushState
info: CoreStateMachine::pushState
info: CoreCommandRouter::volumioPushState
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")', /build/cache/git/checkouts/librespot-6f197fd632ef9380/659de68/playback/src/player.rs:232:9
stack backtrace:
0:   0xaa0828 - backtrace::backtrace::libunwind::trace::h100c6c70e4af496c
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
1:   0xaa0828 - backtrace::backtrace::trace_unsynchronized::hf78ddc194bf45009
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
2:   0xaa0828 - std::sys_common::backtrace::_print_fmt::h967a212a8894e4a4
at src/libstd/sys_common/backtrace.rs:77
3:   0xaa0828 - ::fmt::h5fe383ce2118859a
at src/libstd/sys_common/backtrace.rs:59
4:   0xabc03c - core::fmt::write::h937f59172f6eeeaf
at src/libcore/fmt/mod.rs:1052
5:   0xa9a6ec - std::io::Write::write_fmt::hc70e2634948b89c8
at src/libstd/io/mod.rs:1426
6:   0xaa2cf0 - std::sys_common::backtrace::_print::hbfc81757b29a60f4
at src/libstd/sys_common/backtrace.rs:62
7:   0xaa2cf0 - std::sys_common::backtrace::print::h8bc349c117633211
at src/libstd/sys_common/backtrace.rs:49
8:   0xaa2cf0 - std::panicking::default_hook::{{closure}}::h82c47dcbb8503118
at src/libstd/panicking.rs:204
9:   0xaa2964 - std::panicking::default_hook::hc04800be16711189
at src/libstd/panicking.rs:224
10:   0xaa33a0 - std::panicking::rust_panic_with_hook::h2413ff75e44cd581
at src/libstd/panicking.rs:472
11:   0xaa2fb4 - rust_begin_unwind
at src/libstd/panicking.rs:380
12:   0xab9aa8 - core::panicking::panic_fmt::h2c56481ca2ee7c2f
at src/libcore/panicking.rs:85
volspotconnect2.service: main process exited, code=exited, status=101/n/a
Unit volspotconnect2.service entered failed state.
13:   0xab9904 - core::option::expect_none_failed::ha234f7f2802df4d8
at src/libcore/option.rs:1199
14:   0x6403b8 - librespot_playback::player::Player::load::hd72f67113130cb10
15:   0x5dd260 - librespot_connect::spirc::SpircTask::load_track::hb653d3a5a0ccebdd
16:   0x5db5ac - librespot_connect::spirc::SpircTask::handle_next::hfcdc030e62907eb6
17:   0x5d89d8 - ::poll::h9573d6a1b1bd9fd4
18:   0x531bf0 - ::poll::h15234bb950a4a45a
19:   0x5477e0 - futures::task_impl::std::set::h486e394c1c1653bc
20:   0x55a004 - std::thread::local::LocalKey::with::hab8a1bc0b33c470a
21:   0x5441d0 - tokio_current_thread::Entered
::block_on::h0599a4d0d066ec98
22:   0x559958 - std::thread::local::LocalKey::with::h7df4b0f2f9e67fd8
23:   0x56d8e8 - tokio_reactor::with_default::h406cb9d26e21eb14

24:   0x581a80 - tokio::runtime::current_thread::runtime::Runtime::block_on::h723ea919cc82f819
25:   0x532c04 - vollibrespot::main::h280e0b11e0d9f138
26:   0x56dc84 - std::rt::lang_start::{{closure}}::h14caf76cab139d00
27:   0xaa2e64 - std::rt::lang_start_internal::{{closure}}::habef164db2ffdce8
at src/libstd/rt.rs:52
28:   0xaa2e64 - std::panicking::try::do_call::ha24ef807c5f4c553
at src/libstd/panicking.rs:305
29:   0xaa75f8 - __rust_maybe_catch_panic
at src/libpanic_unwind/lib.rs:86
30:   0xaa37e4 - std::panicking::try::hbf32b3a5688b523f
at src/libstd/panicking.rs:281
31:   0xaa37e4 - std::panic::catch_unwind::haaedb267e2d3c6e6
at src/libstd/panic.rs:394
32:   0xaa37e4 - std::rt::lang_start_internal::hdc1e9a94360026b9
at src/libstd/rt.rs:51
33:   0x533978 - main
34: 0x76c8d294 - __libc_start_main
[Vollibrespot] : Player thread panicked!
[Vollibrespot] : EventSender disconnected
[SpotifyConnect]  Device palyback is inactive
[SpotifyConnect] Device Session is_active: true
[SpotifyConnect]  Sink released
info: CoreCommandRouter::servicePushState
info: CoreStateMachine::pushState
info: CoreCommandRouter::volumioPushState
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
volspotconnect2.service holdoff time over, scheduling restart.
Stopping Volspotconnect2 Daemon...
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.2.1 1438440 2020-05-15 (librespot 659de68 2020-05-10) -- Built On 2020-05-15
Reading Config from "volspotify.toml"
[Vollibrespot] : Using Alsa backend with device: plughw:5
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }`

any ideas?

**Comment by ashthespy** [comment]
```
Invalid value for card [Vollibrespot] : Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ENOENT: No such file or directory' [Vollibrespot] : Could not start audio: Alsa error: PCM open failed ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open)
```

There is your problem, what device/DAC are you trying to use? Its apparently not a valid card..

**Comment by CodingGhost** [comment]
what do you mean with "not a valid card" ? I can play everything just fine, even spotify will play something. I am using a Soundblaster X-fi USB

**Comment by balbuze** [comment]
Do you use a plugin such as equalizer?

**Comment by CodingGhost** [comment]
no, its the only plugin activated

**Comment by CodingGhost** [comment]
If you think It could be a bug (which I do think) I could give you ssh/80 access if you wish to test something.

**Comment by CodingGhost** [comment]
ummmmmm wait. I just figured something out. I will have to redo the log, sorry

**Comment by ashthespy** [comment]
Just a tip for next time.. The configuration for the daemon is in `/data/plugins/music_service/volspotconnect2/volspotify.toml` so you can peek there to ensure that the plugin/volumio api is reporting sane values for the card/mixer..
