### ISSUE TITLE
SpotifyConnect v1.0.5 can't maintain connection on RPi0 with HDMI output

### ISSUE THREAD

**Issue by CtrlAltDel64** [balbuze/volumio-plugins#294]
Hello,

I installed the latest version of volumio on an SD card and am running it successfully on my rpi 0. I was able to install the spotify plugin for playback and successfully play music from the web interface on my rpi 0, with the music being outputted to HDMI => AVR => speakers.

The problem is with getting spotify connect to work. I am able to install it successfully and login to my account (removing multi device use, because I'm not entirely sure how it works and I plan to only use this for myself). I am even able to see my volumio device in spotify connect on my devices (Android phone, Windows 10 spotify apps). The problem is when I connect, I am disconnected shortly after and I'm not able to identify why.

```
Starting Live Log...
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
info: CoreCommandRouter::volumioGetQueue
info: CoreStateMachine::getQueue
info: CorePlayQueue::getQueue
info: CoreCommandRouter::executeOnPlugin: system , getHwuuid
info: CALLMETHOD: system_controller system enableLiveLog true
info: CoreCommandRouter::executeOnPlugin: system , enableLiveLog
info: Launching a new LiveLog session
[Vollibrespot] : Fetching autoplay context uri
[Vollibrespot] : Event: SessionActive { became_active_at: 1609902144020 }
[Vollibrespot] : SessionActive!
[Vollibrespot] : Event: PlaybackStarted { track_id: SpotifyId { id: 339894266019046115990794110304899410463, audio_type: Track } }
[Vollibrespot] : Event: PlaybackLoading { track_id: SpotifyId { id: 339894266019046115990794110304899410463, audio_type: Track } }
thread 'main' panicked at 'Spotify servers returned an error. Restart librespot.', /build/cache/git/checkouts/librespot-6f197fd632ef9380/08d8bcc/core/src/mercury/mod.rs:200:13
stack backtrace:
[SpotifyConnect]  A connect session has begun
[SpotifyConnect]  Device palyback is active!
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
[SpotifyConnect] Currently active: spop
[SpotifyConnect] Stopping currently active service
info: CoreCommandRouter::volumioStop
info: CoreStateMachine::stop
info: CoreStateMachine::setConsumeUpdateService undefined
UNSET VOLATILE
[SpotifyConnect] Vollibrespot Active
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
[SpotifyConnect] Currently active: spop
[SpotifyConnect] Setting Volatile state to Volspotconnect2
info: CoreStateMachine::setConsumeUpdateService undefined
info: CoreCommandRouter::servicePushState
info: CoreStateMachine::pushState
info: CoreCommandRouter::volumioPushState
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
info: CoreCommandRouter::volumioGetState
[SpotifyConnect] Currently active: volspotconnect2
[SpotifyConnect] Pushing new state :: true
info: CoreCommandRouter::servicePushState
info: CoreStateMachine::pushState
info: CoreCommandRouter::volumioPushState
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
0:   0xa1360c - backtrace::backtrace::libunwind::trace::hf9eeeb1d52578408
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1:   0xa1360c - backtrace::backtrace::trace_unsynchronized::h9d71662eece903ab
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
2:   0xa1360c - std::sys_common::backtrace::_print_fmt::h54695504f8601726
at src/libstd/sys_common/backtrace.rs:78
3:   0xa1360c - ::fmt::h512ecf96415d8ce2
at src/libstd/sys_common/backtrace.rs:59
4:   0xa38218 - core::fmt::write::h1060f85d3ee53644
at src/libcore/fmt/mod.rs:1076
5:   0xa0cee0 - std::io::Write::write_fmt::h34e2a8730bb7a876
at src/libstd/io/mod.rs:1537
6:   0xa15c88 - std::sys_common::backtrace::_print::h2be13b0c8dff2c9b
at src/libstd/sys_common/backtrace.rs:62
7:   0xa15c88 - std::sys_common::backtrace::print::hd763058df6eec412
at src/libstd/sys_common/backtrace.rs:49
8:   0xa15c88 - std::panicking::default_hook::{{closure}}::h48b9472d8fc0e6bf
at src/libstd/panicking.rs:198
9:   0xa1593c - std::panicking::default_hook::h0fc1c5596bab0152
at src/libstd/panicking.rs:217
10:   0xa16368 - std::panicking::rust_panic_with_hook::hae7ba177154e198d
at src/libstd/panicking.rs:526
11:   0x71039c - std::panicking::begin_panic::hcf3fa698324ab0fa
volspotconnect2.service: main process exited, code=exited, status=101/n/a
Unit volspotconnect2.service entered failed state.
12:   0x726714 - librespot_core::mercury::MercuryManager::dispatch::hc59e50d9707995e6
13:   0x702be4 - librespot_core::session::Session::dispatch::h37b6fae7d6aa3e81
14:   0x703e60 -  as futures::future::Future>::poll::h0ba8024a390ec885
15:   0x698568 -  as futures::future::Future>::poll::h57369c87de8b3fd5
16:   0x6feb28 -  as futures::future::Future>::poll::h7b35e3cfd7ea8b13
17:   0x75b0ec -  as futures::future::Future>::poll::hcc4f78dbb637f76c
18:   0x4e6b70 - futures::task_impl::std::set::hb8cbae2c116eaf54
19:   0x4d65c0 - tokio_current_thread::CurrentRunner::set_spawn::h97e57c9785ad1c29
20:   0x4f9dc8 - tokio_current_thread::scheduler::Scheduler::tick::h7eb7b655e8807c03
21:   0x4d679c - tokio_current_thread::Entered
::block_on::h2e4ff2c13a247d3c
22:   0x4fb298 - std::thread::local::LocalKey::with::h663fcb2d9f4b6c18
23:   0x5085d4 - tokio_reactor::with_default::h5d8f90b2b875599a
24:   0x4da940 - tokio::runtime::current_thread::runtime::Runtime::block_on::h9505b8c1bab44fab

25:   0x521f98 - vollibrespot::main::h3614a8e14a6045df
26:   0x5092e0 - std::rt::lang_start::{{closure}}::h0a25e89da98ec7db
27:   0xa1672c - std::rt::lang_start_internal::{{closure}}::h97efd249046dc8e8
at src/libstd/rt.rs:52
28:   0xa1672c - std::panicking::try::do_call::h3d07de510dcbc7c8
at src/libstd/panicking.rs:348
29:   0xa1672c - std::panicking::try::hc25ddf66eb022203
at src/libstd/panicking.rs:325
30:   0xa1672c - std::panic::catch_unwind::h36b06962268095b4
at src/libstd/panic.rs:394
31:   0xa1672c - std::rt::lang_start_internal::hdbd4407cfdcc64c8
at src/libstd/rt.rs:51
32:   0x522a54 - main
33: 0xb6d25294 - __libc_start_main
[Vollibrespot] : EventSender disconnected
[SpotifyConnect]  Device palyback is inactive
[SpotifyConnect] Device Session is_active: true
[SpotifyConnect]  Sink released
[SpotifyConnect] Not pushing Pause { active: true, isStopping: true}
[SpotifyConnect] ResolvedStop in [31m 20s 531.69ms [39m
volspotconnect2.service holdoff time over, scheduling restart.
Stopping Volspotconnect2 Daemon...
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.2.2 cd96399 2020-10-07 (librespot 08d8bcc 2020-10-07) -- Built On 2020-10-07
Reading Config from "volspotify.toml"
[Vollibrespot] : Using Alsa backend with device: plughw:0
[Vollibrespot] : Connecting to AP "gew1-accesspoint-b-lclv.ap.spotify.com:443"
[Vollibrespot] : Authenticated as "**********" !
[Vollibrespot] : Setting up new mixer: card:hw:0 mixer:PCM index:0
[Vollibrespot] : Alsa Mixer info min: -10239 (MilliBel(-9999999)[dB]) -- max: 400 (MilliBel(400)[dB]) HW: true
[Vollibrespot] : Using alsa sink
[Vollibrespot] : Metadata pipe established
[Vollibrespot] : Event: Volume { volume_to_mixer: 0 }
[Vollibrespot] : Country: "**"
[SpotifyConnect]  0
[SpotifyConnect] Volume: Spotify:0 Volumio: 0
info: CoreStateMachine::pushState
info: CoreCommandRouter::volumioPushState
info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
info: CALLMETHOD: system_controller system enableLiveLog false
info: CoreCommandRouter::executeOnPlugin: system , enableLiveLog
info: Launching a new LiveLog session
process exited with code null
```

I tried playing around with playback type (hardware, software, none) and having the main spotify plugin uninstalled and installed alongside Spotify Connect plugin with no avail. I did some research online and still am unable to pinpoint the issue. Restarting `systemctl restart volspotconnect2` does not help either.

**Comment by ashthespy** [comment]
Could you share logs from the service directly? The can't see the cause from your log snippet unfortunately..

**Comment by CtrlAltDel64** [comment]
Could you please tell me where I can find these logs? Thank you.

**Comment by ashthespy** [comment]
Full logs since boot, or add the `-f` flag to follow it while you try and connect again..

```
journalctl -u volspotconnect2
```

**Comment by CtrlAltDel64** [comment]
Like this? I followed the logs for my connection attempt.
```
Jan 06 03:27:56 volumio volumio[1438]: Reading Config from "volspotify.toml"
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Using Alsa backend with device: plughw:0
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Connecting to AP "gew1-accesspoint-b-l4jk.ap.spotify.com:443"
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Authenticated as "********" !
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Setting up new mixer: card:hw:0 mixer:PCM index:0
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Alsa Mixer info min: -10239 (MilliBel(-9999999)[dB]) -- max: 400 (MilliBel(400)[dB]) HW: true
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Country: "**"
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Using alsa sink
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Metadata pipe established
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Event: Volume { volume_to_mixer: 0 }
Jan 06 03:33:31 volumio volumio[1438]: [Vollibrespot] : Fetching autoplay context uri
Jan 06 03:33:31 volumio volumio[1438]: [Vollibrespot] : Event: SessionActive { became_active_at: 1609904011207 }
Jan 06 03:33:31 volumio volumio[1438]: [Vollibrespot] : SessionActive!
Jan 06 03:33:31 volumio volumio[1438]: [Vollibrespot] : Event: PlaybackStarted { track_id: SpotifyId { id: 339894266019046115990794110304899410463, audio_type: Track } }
Jan 06 03:33:31 volumio volumio[1438]: [Vollibrespot] : Event: PlaybackLoading { track_id: SpotifyId { id: 339894266019046115990794110304899410463, audio_type: Track } }
Jan 06 03:33:31 volumio volumio[1438]: thread 'main' panicked at 'Spotify servers returned an error. Restart librespot.', /build/cache/git/checkouts/librespot-6f197fd632ef9380/08d8bcc/core/src/mercury/mod.rs:200:13
Jan 06 03:33:31 volumio volumio[1438]: stack backtrace:
Jan 06 03:33:31 volumio volumio[1438]: 0:   0xa7260c - backtrace::backtrace::libunwind::trace::hf9eeeb1d52578408
Jan 06 03:33:31 volumio volumio[1438]: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
Jan 06 03:33:31 volumio volumio[1438]: 1:   0xa7260c - backtrace::backtrace::trace_unsynchronized::h9d71662eece903ab
Jan 06 03:33:31 volumio volumio[1438]: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
Jan 06 03:33:31 volumio volumio[1438]: 2:   0xa7260c - std::sys_common::backtrace::_print_fmt::h54695504f8601726
Jan 06 03:33:31 volumio volumio[1438]: at src/libstd/sys_common/backtrace.rs:78
Jan 06 03:33:31 volumio volumio[1438]: 3:   0xa7260c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h512ecf96415d8ce2
Jan 06 03:33:31 volumio volumio[1438]: at src/libstd/sys_common/backtrace.rs:59
Jan 06 03:33:31 volumio volumio[1438]: 4:   0xa97218 - core::fmt::write::h1060f85d3ee53644
Jan 06 03:33:31 volumio volumio[1438]: at src/libcore/fmt/mod.rs:1076
Jan 06 03:33:31 volumio volumio[1438]: 5:   0xa6bee0 - std::io::Write::write_fmt::h34e2a8730bb7a876
Jan 06 03:33:31 volumio volumio[1438]: at src/libstd/io/mod.rs:1537
Jan 06 03:33:31 volumio volumio[1438]: 6:   0xa74c88 - std::sys_common::backtrace::_print::h2be13b0c8dff2c9b
Jan 06 03:33:32 volumio volumio[1438]: at src/libstd/sys_common/backtrace.rs:62
Jan 06 03:33:32 volumio volumio[1438]: 7:   0xa74c88 - std::sys_common::backtrace::print::hd763058df6eec412
Jan 06 03:33:32 volumio volumio[1438]: at src/libstd/sys_common/backtrace.rs:49
Jan 06 03:33:32 volumio volumio[1438]: 8:   0xa74c88 - std::panicking::default_hook::{{closure}}::h48b9472d8fc0e6bf
Jan 06 03:33:32 volumio volumio[1438]: at src/libstd/panicking.rs:198
Jan 06 03:33:32 volumio volumio[1438]: 9:   0xa7493c - std::panicking::default_hook::h0fc1c5596bab0152
Jan 06 03:33:32 volumio volumio[1438]: at src/libstd/panicking.rs:217
Jan 06 03:33:32 volumio volumio[1438]: 10:   0xa75368 - std::panicking::rust_panic_with_hook::hae7ba177154e198d
Jan 06 03:33:32 volumio volumio[1438]: at src/libstd/panicking.rs:526
Jan 06 03:33:32 volumio volumio[1438]: 11:   0x76f39c - std::panicking::begin_panic::hcf3fa698324ab0fa
Jan 06 03:33:32 volumio volumio[1438]: 12:   0x785714 - librespot_core::mercury::MercuryManager::dispatch::hc59e50d9707995e6
Jan 06 03:33:32 volumio volumio[1438]: 13:   0x761be4 - librespot_core::session::Session::dispatch::h37b6fae7d6aa3e81
Jan 06 03:33:32 volumio volumio[1438]: 14:   0x762e60 - <librespot_core::session::DispatchTask<S> as futures::future::Future>::poll::h0ba8024a390ec885
Jan 06 03:33:32 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Jan 06 03:33:32 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
Jan 06 03:33:32 volumio volumio[1438]: 15:   0x6f7568 - <futures::future::join::Join<A,B> as futures::future::Future>::poll::h57369c87de8b3fd5
Jan 06 03:33:32 volumio volumio[1438]: 16:   0x75db28 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h7b35e3cfd7ea8b13
Jan 06 03:33:32 volumio volumio[1438]: 17:   0x7ba0ec - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::hcc4f78dbb637f76c
Jan 06 03:33:32 volumio volumio[1438]: 18:   0x545b70 - futures::task_impl::std::set::hb8cbae2c116eaf54
Jan 06 03:33:32 volumio volumio[1438]: 19:   0x5355c0 - tokio_current_thread::CurrentRunner::set_spawn::h97e57c9785ad1c29
Jan 06 03:33:32 volumio volumio[1438]: 20:   0x558dc8 - tokio_current_thread::scheduler::Scheduler<U>::tick::h7eb7b655e8807c03
Jan 06 03:33:32 volumio volumio[1438]: 21:   0x53579c - tokio_current_thread::Entered<P>::block_on::h2e4ff2c13a247d3c
Jan 06 03:33:32 volumio volumio[1438]: 22:   0x55a298 - std::thread::local::LocalKey<T>::with::h663fcb2d9f4b6c18
Jan 06 03:33:32 volumio volumio[1438]: 23:   0x5675d4 - tokio_reactor::with_default::h5d8f90b2b875599a
Jan 06 03:33:32 volumio volumio[1438]: 24:   0x539940 - tokio::runtime::current_thread::runtime::Runtime::block_on::h9505b8c1bab44fabJan 06 03:33:32 volumio volumio[1438]: 25:   0x580f98 - vollibrespot::main::h3614a8e14a6045df
Jan 06 03:33:32 volumio volumio[1438]: 26:   0x5682e0 - std::rt::lang_start::{{closure}}::h0a25e89da98ec7db
Jan 06 03:33:32 volumio volumio[1438]: 27:   0xa7572c - std::rt::lang_start_internal::{{closure}}::h97efd249046dc8e8
Jan 06 03:33:32 volumio volumio[1438]: at src/libstd/rt.rs:52
Jan 06 03:33:32 volumio volumio[1438]: 28:   0xa7572c - std::panicking::try::do_call::h3d07de510dcbc7c8
Jan 06 03:33:32 volumio volumio[1438]: at src/libstd/panicking.rs:348
Jan 06 03:33:32 volumio volumio[1438]: 29:   0xa7572c - std::panicking::try::hc25ddf66eb022203
Jan 06 03:33:32 volumio volumio[1438]: at src/libstd/panicking.rs:325
Jan 06 03:33:32 volumio volumio[1438]: 30:   0xa7572c - std::panic::catch_unwind::h36b06962268095b4
Jan 06 03:33:32 volumio volumio[1438]: at src/libstd/panic.rs:394
Jan 06 03:33:32 volumio volumio[1438]: 31:   0xa7572c - std::rt::lang_start_internal::hdbd4407cfdcc64c8
Jan 06 03:33:32 volumio volumio[1438]: at src/libstd/rt.rs:51
Jan 06 03:33:32 volumio volumio[1438]: 32:   0x581a54 - main
Jan 06 03:33:32 volumio volumio[1438]: 33: 0xb6cd0294 - __libc_start_main
Jan 06 03:33:32 volumio volumio[1438]: [Vollibrespot] : EventSender disconnected
Jan 06 03:33:34 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Jan 06 03:33:34 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
Jan 06 03:33:34 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Jan 06 03:33:34 volumio systemd[1]: Started Volspotconnect2 Daemon.
Jan 06 03:33:34 volumio volumio[2257]: vollibrespot v0.2.2 cd96399 2020-10-07 (librespot 08d8bcc 2020-10-07) -- Built On 2020-10-07
Jan 06 03:33:34 volumio volumio[2257]: Reading Config from "volspotify.toml"
Jan 06 03:33:34 volumio volumio[2257]: [Vollibrespot] : Using Alsa backend with device: plughw:0
Jan 06 03:33:34 volumio volumio[2257]: [Vollibrespot] : Connecting to AP "gew1-accesspoint-b-ntdr.ap.spotify.com:443"
Jan 06 03:33:34 volumio volumio[2257]: [Vollibrespot] : Authenticated as "***********" !
Jan 06 03:33:34 volumio volumio[2257]: [Vollibrespot] : Setting up new mixer: card:hw:0 mixer:PCM index:0
Jan 06 03:33:34 volumio volumio[2257]: [Vollibrespot] : Alsa Mixer info min: -10239 (MilliBel(-9999999)[dB]) -- max: 400 (MilliBel(400)[dB]) HW: true
Jan 06 03:33:34 volumio volumio[2257]: [Vollibrespot] : Country: "**"
Jan 06 03:33:35 volumio volumio[2257]: [Vollibrespot] : Using alsa sink
Jan 06 03:33:35 volumio volumio[2257]: [Vollibrespot] : Metadata pipe established
Jan 06 03:33:35 volumio volumio[2257]: [Vollibrespot] : Event: Volume { volume_to_mixer: 0 }
```

**Comment by CtrlAltDel64** [comment]
Could it be an issue with incorrect Alsa output selection by spotifyconnect?

**Comment by ashthespy** [comment]
Hmm, does this happen for all tracks you try? 


```
Spotify servers returned an error. Restart librespot.
```

**Comment by ashthespy** [comment]
> Could it be an issue with incorrect Alsa output selection by spotifyconnect?

Nope that part is all good.
```
 [Vollibrespot] : Setting up new mixer: card:hw:0 mixer:PCM index:0
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Alsa Mixer info min: -10239 (MilliBel(-9999999)[dB]) -- max: 400 (MilliBel(400)[dB]) HW: true
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Country: "**"
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Using alsa sink
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Metadata pipe established
Jan 06 03:27:56 volumio volumio[1438]: [Vollibrespot] : Event: Volume { volume_to_mixer: 0 }
Jan 06 03:33:31 volumio volumio[1438]: [Vollibrespot] : Fetching autoplay context uri
```

**Comment by CtrlAltDel64** [comment]
> Hmm, does this happen for all tracks you try?
> 
> ```
> Spotify servers returned an error. Restart librespot.

Thank you for the pointer. The issue was with the track. I played around with spotify a bit more and found another crash.

I am finally able to pinpoint the issue: If you have a self-created playlist and you scroll down to "recommended songs", playing any one of those songs will crash the plugin. This is something I can most definitely live without, but I thought I would let you know the end result. 

Here are the new logs:
(explanation: the last song in my own playlist is "Arms Around You". Shortly after, I press a song that is in the "Recommended Songs" list and the plugin crashes).
```
Jan 06 03:54:23 volumio volumio[5255]: [Vollibrespot] : Fetching autoplay context uri
Jan 06 03:54:24 volumio volumio[5255]: [Vollibrespot] : Event: TrackChanged { old_track_id: SpotifyId { id: 272908311127598645025010045552308396934, audio_type: Track }, track_id: SpotifyId { id: 120778330510654573414253347871719063499, audio_type: Track } }
Jan 06 03:54:24 volumio volumio[5255]: [Vollibrespot] : Autoplay uri resolved to <"spotify:station:playlist:*******"> Jan 06 03:54:24 volumio volumio[5255]: [Vollibrespot] : Resolving uri "spotify:station:playlist:*******"
Jan 06 03:54:24 volumio volumio[5255]: [Vollibrespot] : Resolved 50 tracks from <"spotify:playlist:****">
Jan 06 03:54:24 volumio volumio[5255]: [Vollibrespot] : Loading <Arms Around You (feat. Maluma & Swae Lee)> with Spotify URI <spotify:track:2LskIZrCeLxRvCiGP8gxlh>
Jan 06 03:54:24 volumio volumio[5255]: [Vollibrespot] : Event: SinkInactive
Jan 06 03:54:24 volumio volumio[5255]: [Vollibrespot] : Event: PlaybackLoading { track_id: SpotifyId { id: 120778330510654573414253347871719063499, audio_type: Track } }
Jan 06 03:54:24 volumio volumio[5255]: [Vollibrespot] : <Arms Around You (feat. Maluma & Swae Lee)> (198902 ms) loaded
Jan 06 03:54:24 volumio volumio[5255]: [Vollibrespot] : Event: SinkActive
Jan 06 03:54:25 volumio volumio[5255]: [Vollibrespot] : Fetching autoplay context uri
Jan 06 03:54:25 volumio volumio[5255]: [Vollibrespot] : Event: TrackChanged { old_track_id: SpotifyId { id: 120778330510654573414253347871719063499, audio_type: Track }, track_id: SpotifyId { id: 335083105422969055265693243785872488056, audio_type: Track } }
Jan 06 03:54:25 volumio volumio[5255]: thread 'main' panicked at 'Spotify servers returned an error. Restart librespot.', /build/cache/git/checkouts/librespot-6f197fd632ef9380/08d8bcc/core/src/mercury/mod.rs:200:13
Jan 06 03:54:26 volumio volumio[5255]: stack backtrace:
Jan 06 03:54:26 volumio volumio[5255]: 0:   0xa0e60c - backtrace::backtrace::libunwind::trace::hf9eeeb1d52578408
Jan 06 03:54:26 volumio volumio[5255]: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
Jan 06 03:54:26 volumio volumio[5255]: 1:   0xa0e60c - backtrace::backtrace::trace_unsynchronized::h9d71662eece903ab
Jan 06 03:54:26 volumio volumio[5255]: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
Jan 06 03:54:26 volumio volumio[5255]: 2:   0xa0e60c - std::sys_common::backtrace::_print_fmt::h54695504f8601726
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/sys_common/backtrace.rs:78
Jan 06 03:54:26 volumio volumio[5255]: 3:   0xa0e60c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h512ecf96415d8ce2
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/sys_common/backtrace.rs:59
Jan 06 03:54:26 volumio volumio[5255]: 4:   0xa33218 - core::fmt::write::h1060f85d3ee53644
Jan 06 03:54:26 volumio volumio[5255]: at src/libcore/fmt/mod.rs:1076
Jan 06 03:54:26 volumio volumio[5255]: 5:   0xa07ee0 - std::io::Write::write_fmt::h34e2a8730bb7a876
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/io/mod.rs:1537
Jan 06 03:54:26 volumio volumio[5255]: 6:   0xa10c88 - std::sys_common::backtrace::_print::h2be13b0c8dff2c9b
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/sys_common/backtrace.rs:62
Jan 06 03:54:26 volumio volumio[5255]: 7:   0xa10c88 - std::sys_common::backtrace::print::hd763058df6eec412
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/sys_common/backtrace.rs:49
Jan 06 03:54:26 volumio volumio[5255]: 8:   0xa10c88 - std::panicking::default_hook::{{closure}}::h48b9472d8fc0e6bf
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/panicking.rs:198
Jan 06 03:54:26 volumio volumio[5255]: 9:   0xa1093c - std::panicking::default_hook::h0fc1c5596bab0152
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/panicking.rs:217
Jan 06 03:54:26 volumio volumio[5255]: 10:   0xa11368 - std::panicking::rust_panic_with_hook::hae7ba177154e198d
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/panicking.rs:526
Jan 06 03:54:26 volumio volumio[5255]: 11:   0x70b39c - std::panicking::begin_panic::hcf3fa698324ab0fa
Jan 06 03:54:26 volumio volumio[5255]: 12:   0x721714 - librespot_core::mercury::MercuryManager::dispatch::hc59e50d9707995e6
Jan 06 03:54:26 volumio volumio[5255]: 13:   0x6fdbe4 - librespot_core::session::Session::dispatch::h37b6fae7d6aa3e81
Jan 06 03:54:26 volumio volumio[5255]: 14:   0x6fee60 - <librespot_core::session::DispatchTask<S> as futures::future::Future>::poll::h0ba8024a390ec885
Jan 06 03:54:26 volumio volumio[5255]: 15:   0x693568 - <futures::future::join::Join<A,B> as futures::future::Future>::poll::h57369c87de8b3fd5
Jan 06 03:54:26 volumio volumio[5255]: 16:   0x6f9b28 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h7b35e3cfd7ea8b13
Jan 06 03:54:26 volumio volumio[5255]: 17:   0x7560ec - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::hcc4f78dbb637f76c
Jan 06 03:54:26 volumio volumio[5255]: 18:   0x4e1b70 - futures::task_impl::std::set::hb8cbae2c116eaf54
Jan 06 03:54:26 volumio volumio[5255]: 19:   0x4d15c0 - tokio_current_thread::CurrentRunner::set_spawn::h97e57c9785ad1c29
Jan 06 03:54:26 volumio volumio[5255]: 20:   0x4f4dc8 - tokio_current_thread::scheduler::Scheduler<U>::tick::h7eb7b655e8807c03
Jan 06 03:54:26 volumio volumio[5255]: 21:   0x4d179c - tokio_current_thread::Entered<P>::block_on::h2e4ff2c13a247d3c
Jan 06 03:54:26 volumio volumio[5255]: 22:   0x4f6298 - std::thread::local::LocalKey<T>::with::h663fcb2d9f4b6c18
Jan 06 03:54:26 volumio volumio[5255]: 23:   0x5035d4 - tokio_reactor::with_default::h5d8f90b2b875599a
Jan 06 03:54:26 volumio volumio[5255]: 24:   0x4d5940 - tokio::runtime::current_thread::runtime::Runtime::block_on::h9505b8c1bab44fabJan 06 03:54:26 volumio volumio[5255]: 25:   0x51cf98 - vollibrespot::main::h3614a8e14a6045df
Jan 06 03:54:26 volumio volumio[5255]: 26:   0x5042e0 - std::rt::lang_start::{{closure}}::h0a25e89da98ec7db
Jan 06 03:54:26 volumio volumio[5255]: 27:   0xa1172c - std::rt::lang_start_internal::{{closure}}::h97efd249046dc8e8
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/rt.rs:52
Jan 06 03:54:26 volumio volumio[5255]: 28:   0xa1172c - std::panicking::try::do_call::h3d07de510dcbc7c8
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/panicking.rs:348
Jan 06 03:54:26 volumio volumio[5255]: 29:   0xa1172c - std::panicking::try::hc25ddf66eb022203
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/panicking.rs:325
Jan 06 03:54:26 volumio volumio[5255]: 30:   0xa1172c - std::panic::catch_unwind::h36b06962268095b4
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/panic.rs:394
Jan 06 03:54:26 volumio volumio[5255]: 31:   0xa1172c - std::rt::lang_start_internal::hdbd4407cfdcc64c8
Jan 06 03:54:26 volumio volumio[5255]: at src/libstd/rt.rs:51
Jan 06 03:54:26 volumio volumio[5255]: 32:   0x51da54 - main
Jan 06 03:54:26 volumio volumio[5255]: 33: 0xb6d00294 - __libc_start_main
```

**Comment by ashthespy** [comment]
Will investigate :-) thanks!

**Comment by CtrlAltDel64** [comment]
Solution: Unable to play "Recommended Songs" from custom-made playlists with current version.
